version: "3.9"
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "0.0.0.0"]
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - redis
